/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskRouteImport } from './routes/task'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskIndexRouteImport } from './routes/task.index'
import { Route as TaskProjectIdRouteImport } from './routes/task.$projectId'

const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIndexRoute = TaskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaskRoute,
} as any)
const TaskProjectIdRoute = TaskProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => TaskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task': typeof TaskRouteWithChildren
  '/task/$projectId': typeof TaskProjectIdRoute
  '/task/': typeof TaskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task/$projectId': typeof TaskProjectIdRoute
  '/task': typeof TaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/task': typeof TaskRouteWithChildren
  '/task/$projectId': typeof TaskProjectIdRoute
  '/task/': typeof TaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task' | '/task/$projectId' | '/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task/$projectId' | '/task'
  id: '__root__' | '/' | '/task' | '/task/$projectId' | '/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskRoute: typeof TaskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/': {
      id: '/task/'
      path: '/'
      fullPath: '/task/'
      preLoaderRoute: typeof TaskIndexRouteImport
      parentRoute: typeof TaskRoute
    }
    '/task/$projectId': {
      id: '/task/$projectId'
      path: '/$projectId'
      fullPath: '/task/$projectId'
      preLoaderRoute: typeof TaskProjectIdRouteImport
      parentRoute: typeof TaskRoute
    }
  }
}

interface TaskRouteChildren {
  TaskProjectIdRoute: typeof TaskProjectIdRoute
  TaskIndexRoute: typeof TaskIndexRoute
}

const TaskRouteChildren: TaskRouteChildren = {
  TaskProjectIdRoute: TaskProjectIdRoute,
  TaskIndexRoute: TaskIndexRoute,
}

const TaskRouteWithChildren = TaskRoute._addFileChildren(TaskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskRoute: TaskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
